services:
  apache:
    build: .
    container_name: php-apache
    ports:
      - '3000:80'
    volumes:
      - ./app:/var/www/html  # Montar solo `app` en el contenedor
    networks:
      - entorno-web
    depends_on:
      - mysql

  mysql:
    image: mysql:5.6
    container_name: bbdd
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=transfer
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    networks:
      - entorno-web
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      - PMA_HOST=mysql
    networks:
      - entorno-web

networks:
  entorno-web:

volumes:
  mysql_data:
